name: cd

on:
  push:
    paths:
      - "infra/**"

env:
  AWS_REGION: eu-west-3

defaults:
  run:
    working-directory: infra

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.1.0

    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
